#! /bin/bash
#$ -q hpc@@colon
#$ -pe smp 1
#$ -N jobname

export RASPA_DIR=${HOME}/RASPA/simulations/
export DYLD_LIBRARY_PATH=${RASPA_DIR}/lib
export LD_LIBRARY_PATH=${RASPA_DIR}/lib
$RASPA_DIR/bin/simulate -i N2.input
